apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - database/postgres.yaml
  - storage/s3-storage.yaml
  - auth/keycloak.yaml
  - observability/victoriametrics.yaml
  - observability/grafana.yaml
  - observability/litellm.yaml
  - observability/loki.yaml
  - ai/clip-service.yaml
  - velura/velura-api.yaml
  - velura/velura-storefront.yaml
  - velura/velura-admin.yaml
  - networking/cloudflared.yaml
  - networking/oauth2-proxy.yaml
