apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-restore-drill
  namespace: database
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.10
  bootstrap:
    recovery:
      source: archive
  externalClusters:
  - name: archive
    plugin:
      name: barman-cloud.cloudnative-pg.io
      parameters:
        barmanObjectName: external-keycloak-backup
        serverName: keycloak-pg
  storage:
    size: 20Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 768Mi
